title: Full Stack Mini Course
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - how_to_setup_a_java_development_environment.md
header_pages:

theme: jekyll-theme-architect