runtime: java11

handlers:
  # serve static content from the static folder
  - url: (/.*)
    static_files: BOOT-INF/classes/static\1
    upload: BOOT-INF/classes/static/.*\.(gif|png|jpg|svg|ico|css|js|html)$
    require_matching_file: True
    login: optional
    secure: optional

  # set the default document to index.html for all folders
  - url: /(.+)/
    static_files: BOOT-INF/classes/static/\1/index.html
    upload: BOOT-INF/classes/static/(.+)/index.html
    require_matching_file: True
    login: optional
    secure: optional

  # set the default document for the domain root
  - url: /
    static_files: BOOT-INF/classes/static/index.html
    upload: BOOT-INF/classes/static/index.html
    require_matching_file: True
    login: optional
    secure: optional