runtime: java11

entrypoint: java -noverify BOOT-INF/resources/:BOOT-INF/classes/:BOOT-INF/lib/* com.fullstackclouddeveloper.landingpageservice.LandingPageServiceApplication

handlers:
  # serve static content from the static folder
  - url: (/.*)
    static_files: BOOT-INF/classes/static\1
    upload: BOOT-INF/classes/static/.*\.(gif|png|jpg|svg|ico|css|js|html)$
    require_matching_file: True
    login: optional
    secure: optional

  # index files
  - url: /(.+)/
    static_files: BOOT-INF/classes/static/\1/index.html
    upload: BOOT-INF/classes/static/(.+)/index.html
    login: optional
    secure: optional

  - url: /(.+)
    static_files: BOOT-INF/classes/static/\1/index.html
    upload: BOOT-INF/classes/static/(.+)/index.html
    login: optional
    secure: optional

  # site root
  - url: /
    static_files: BOOT-INF/classes/static/index.html
    upload: BOOT-INF/classes/static/index.html
    login: optional
    secure: optional
